apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  source:
    chart: "aws-load-balancer-controller"
    repoURL: "https://aws.github.io/eks-charts"
    targetRevision: 1.6.2
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        region: us-east-2
        image:
          repository: 602401143452.dkr.ecr.us-east-2.amazonaws.com/amazon/aws-load-balancer-controller
        serviceAccount:
          create: false
          name: aws-load-balancer-controller
        clusterName: xyz-cluster
        keepTLSSecret: True
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system