apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  source:
    chart: "external-dns"
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 6.28.4
    helm:
      releaseName: external-dns
      values: |
        sources: 
        - "service"
        - "ingress"
        domainFilters: 
        - "zyonash.com"
        provider: aws
        txtOwnerId: xyz
        policy: sync
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system