apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xyz-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: xyz-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: xyz