---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: xyz-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xyz-app
    spec:
      containers:
        - name: xyz
          image: {{ .Values.imageRegistry }}/xyz-images:{{ .Values.dockerTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: app-port
              containerPort: 80