name: 'Smoke test'

on:
  workflow_dispatch:

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Install Go
        run: | 
          wget https://dl.google.com/go/go1.21.4.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
      - name: Run smoke test
        run: make testCluster