name: 'Smoke test'

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::568903012602:role/provisioner
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Setup Go 1.21.4
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - name: Run smoke test
        run: make testCluster