name: 'Smoke test'

on:
  workflow_dispatch:

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.4' ]
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run smoke test
        run: make testCluster