name: 'Test application'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  workflow_dispatch:
  pull_request:
    types: 
      - opened
      - reopened 
    branches:
      - 'main'
jobs:
  test_application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - run: make build
      - run: make test